// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function KillWorker() {
  return window['go']['main']['App']['KillWorker']();
}

export function StartWorker() {
  return window['go']['main']['App']['StartWorker']();
}
